name: Run Pytest

on: [push, pull_request]  # Triggers on any push or pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]  # assuming you defined 'test' extras in pyproject.toml
        pip install pytest

    - name: 🧪 Run tests
      run: |
        pytest
